# Python CircleCI 2.1 configuration file
version: 2.1
orbs:
  slack: circleci/slack@4.3.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator

      - run:
          name: run coverage
          command: |
            . venv/bin/activate
            poetry run pytest -v --cov --cov-report xml:coverage.xml
            bash <(curl -s https://codecov.io/bash) -t $CODECOV -f coverage.xml -v
